[package]
name = "sawtooth-raft"
version = "0.1.0"
authors = ["Intel Corporation"]

[dependencies]
clap = "2"
log = "0.4"
protobuf = "2"
raft = "0.3.0"
sawtooth_sdk = { path = "../sawtooth-core/sdk/rust" }
simple_logger = "0.5"
